### ISSUE TITLE
"Redux Store has not been initialized" if UiFramework initialized with custom store

### ISSUE THREAD

**Issue by MichaelBelousov** [imodeljs/itwin-viewer#62]
Maybe I'm doing something wrong here, but I am initializing UiFramework with a custom store instance, and as a result the Viewer component throws this error:

```
BentleyError.ts:400 Uncaught Error: Redux Store has not been initialized
    at Function.get store [as store] (StateManager.ts:89)
    at IModelLoader.tsx:247
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at updateSimpleMemoComponent (react-dom.development.js:16972)
    at beginWork (react-dom.development.js:18687)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at scheduleUpdateOnFiber (react-dom.development.js:21199)
    at dispatchAction (react-dom.development.js:15660)
    at getModelConnection (IModelLoader.tsx:161)
```

My cursory understanding is that itwin-viewer-react erroneously uses StateManager's store reference when it should be using UiFramework's store reference which allows both. Otherwise I don't know much about StateManager's role.

I am using this workaround in the meanwhile:
```tsx
await UiFramework.initialize(store, IModelApp.i18n);
// SEE: https://github.com/imodeljs/viewer-components-react/issues/74
(StateManager as any)._singletonStore = store;
```

**Comment by aruniverse** [comment]
Im surprised you're hitting this error, as the itwin-viewer should in fact be initializing UiFramework, look [here](https://github.com/imodeljs/itwin-viewer/blob/master/packages/modules/itwin-viewer-react/src/services/Initializer.ts#L203).

One thing we should probably be doing is exposing the StateManager so consumers can add their own stores to it.

**Comment by MichaelBelousov** [comment]
this seems to be the culprit to me https://github.com/imodeljs/itwin-viewer/blob/f255deea50a678140a4a6ac28b04dcb615650614/packages/modules/itwin-viewer-react/src/components/iModel/IModelLoader.tsx#L247
If you can use the UiFramework.store instead, it would default to StateManager.store if no custom store is used. But that might be naive, I'm not sure what else is going on

**Comment by kckst8** [comment]
@aruniverse hit the nail on the head here. The main idea behind the viewer is that consumers should not need to worry about initializing all of the statics in iModel.js. It assumes that consumers would not be calling initialize. That said, we still want to support parameters for the statics where necessary. It seems like maybe we should allow for users to pass in custom stores?

We can also change the above code if you think that will fix your issues in the short term. Have you verified that this resolves it?

**Comment by MichaelBelousov** [comment]
I think the best option is to be able to pass a custom store which is what I initially thought would be a prop of the viewer. I do initialize everything myself which I sort of didn't realize I didn't need to do, I have custom rpcs and packages that need to be initialized, and I'm not sure which are or aren't already initialized by itwin-viewer. I believe I need the custom store for itwin-saved-views to work, although I should double check that.

**Comment by aruniverse** [comment]
I think Mike should initialize his customs rpcs and static in the post-startup callback in order to not initialize any of the core imjs statics. If theres specific parameters to the core statics he needs to override, we should expose that.

Rather than passing in a custom store to use I think we should try to make use of Core's [ReducerRegistry](https://www.itwinjs.org/reference/ui-framework/state/reducerregistry/ ) so we can dynamically add to the StateManager.

**Comment by MichaelBelousov** [comment]
Out of scope of this thread but while I'm changing it, is it not possible to pass a custom i18n instance to IModelApp.startup using itwin-viewer? It looks like it's always explicitly created for you. I'd like to be able to use translations before the Viewer component is rendered, any suggestions? I18next is static so it's possible but I'm not sure how that interacts with IModelApp's usage of it.

**Comment by MichaelBelousov** [comment]
Closing and will register reducers myself as @aruniverse suggested.
