### ISSUE TITLE
Keyin "restore frontstage layout" results in couldNotFindTool error.

### ISSUE THREAD

**Issue by billyd-at-bentley** [imodeljs/itwin-viewer#80]
I was trying to clear my frontstage cache using "restore frontstage layout", but it resulted in the error shown in this screenshot: https://gyazo.com/e5a6fb1bb08de1c62c99507b6b968e0a .

**Comment by aruniverse** [comment]
Just in case anyone else hits this error on their end. Please run a build of your viewer app. This should copy over the files required to use the key-in.
